### ISSUE TITLE
Charset and Umlauts

### ISSUE THREAD

**Issue by exophunk** [boboldehampsink/export#15]
Hi Bob, I have a little question,

When I export data with Umlauts (ä, ü, ö), they don't get displayed correctly when I open the CSV file in excel. Is there any place where I can define the correct charset (UTF-8?) to use or something, so this doesn't happen? I am using a custom export service, so could I add something there?

Thanks...

**Comment by boboldehampsink** [comment]
Craft already uses UTF-8. What happens if you open it in an other program, such as a text editor (to view the source) or in Google Docs? There are many known issues with Excel and UTF-8.

Also, see this article: http://stackoverflow.com/questions/6002256/is-it-possible-to-force-excel-recognize-utf-8-csv-files-automatically
